<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>12.0</LangVersion>
    <IsPackable>false</IsPackable>
    <AssemblyName>GameQuest</AssemblyName>
    <RootNamespace>GameQuest</RootNamespace>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Shared/GameQuest.Shared.csproj" />
    <ProjectReference Include="Client/GameQuest.Client.csproj" />
    <ProjectReference Include="Server/Configuration/GameQuest.Server.Configuration.csproj" />
    <ProjectReference Include="Server/GameApi/GameQuest.GameApi.csproj" />
    <ProjectReference Include="Server/QuestMission/GameQuest.QuestMission.csproj" />
  </ItemGroup>
</Project>
