<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <RootNamespace>QuickStart.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Zlink.Framework" />
    <PackageReference Include="Zlink.Framework.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Shared/Shared.csproj" />
  </ItemGroup>

</Project>
